'use client'

import type { AgentAlertsRow } from "@/lib/types/database.types"

type Props = {
  unreadAlerts: AgentAlertsRow[]
}

export function ContextSummaryCard({ unreadAlerts }: Props) {
  const unreadCount = unreadAlerts.length

  return (
    <div className="space-y-2 rounded-xl border border-green-100 bg-white p-3 text-[11px] shadow-sm">
      <p className="font-semibold text-green-900">
        Daily digest &amp; alerts
      </p>
      {unreadCount === 0 ? (
        <p className="text-gray-600">
          No unread alerts. You&apos;re all caught up.
        </p>
      ) : (
        <>
          <p className="text-gray-700">
            You have{" "}
            <span className="font-semibold">
              {unreadCount} unread alert
              {unreadCount > 1 ? "s" : ""}
            </span>{" "}
            from the agent.
          </p>
          <ul className="space-y-1 text-gray-700">
            {unreadAlerts.slice(0, 3).map((a) => (
              <li key={a.id}>{a.title}</li>
            ))}
          </ul>
        </>
      )}
      <p className="text-[10px] text-gray-500">
        Alerts are generated by the daily digest and price alerts
        when important changes happen.
      </p>
    </div>
  )
}

